Feature/trainingsessie overhaul
Mees-H/SCRUM-SOp pull request #109
Opened 2023-06-19 10:26 UTC by EvaVanGurp

# Definition of Done

## Functionele definities 

- [x] De acceptatiecriteria van de user story zijn gehaald. 

- [x] Elk stuk werk is nagekeken door minimaal 2 andere programmeurs. 

- [ ] Het programma wordt getest en werkt op 2 verschillende browsers (Google Chrome & Edge). 

### Toegankelijkheid 

- [z] De website moet voor iedereen te navigeren zijn. 

- [z] Inclusief mensen met een beperking. 

- [x] De website dient volledig navigeerbaar te zijn zonder gebruik te maken van een muis. 

- [x] Dit betekent navigeren via de tab en enter toets met behulp van spraak. 

- [x] De knoppen zijn voorzien van duidelijke beschrijvingen. 

- [x] De knoppen zijn groot genoeg om de tekst te bevatten. 

- [x] De teksten op de website bevatten geen spelfouten en zijn duidelijk geformuleerd. 

- [x] Zorg voor voldoende contrast. 

- [x] Contrast wordt getest met deze tool: https://webaim.org/resources/contrastchecker/  

- [x] De WCAG AAA test moet pass teruggeven. 

- [x] Maak geen gebruik van hyperlinks met een klik hier maar gebruik een betekenisvolle beschrijving.  

Zoals: Lees meer over regulering. 

- [x] Maak korte en inhoudelijke pagina’s. 

## Technische definities 

### Reviewers 

- [ ] Elke pull request is door minimaal 2 personen nagekeken. 

- [ ] Een taak wordt pas als af beschouwd zodra hij is goedgekeurd door de 2 reviewers en samengevoegd is op de juiste branch. 

- [ ] De reviewer doorloopt de happy flow. 

- [ ] Hierbij maakt de reviewer gebruik van de juiste werkwijze van de website. 

- [ ] De reviewer probeert d.m.v. onjuist gebruik van de website de website te breken. 

- [ ] Dit kan hij/zij doen door verkeerde invoer van velden. 

- [ ] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

### Ontwikkelaar 

- [x] Er is geen SQL injection mogelijk  

- [ ] Alle invoervelden zijn voorzien van een regex. 

- [ ] Deze regex zorgt ervoor dat alleen het noodzakelijke ingevoerd kan worden. 

- [x] De coding guidlines zijn aangehouden. 

- [x] De geschreven code compileert. 

- [x] De geschreven code veroorzaakt geen crashes. 

- [x] Code levert geen complicaties op met de AVG-wetgeving. 

- [x] Dusk tests worden geschreven voor de happy flow en minimaal 1 bad flow. 

- [x] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

- [x] De siteMap en navigatiebalk zijn geüpdatet op basis van de aanpassingen. 

### Toegankelijkheid 

- [x] Houd je aan de standaarden voor het web. 

- [x] De website moet door gebruik van tab te navigeren zijn. 

- [x] Voeg een alt-tekst toe bij niet-tekstuele-content met betekenisvolle informatie. 

- [x] Maak geen gebruik van spaties. 

- [x] De knoppen hebben een minimaal formaat van 21x30px. 

- [x] Maak gebruik van een rustige layout. 

- [x] Maak gebruik van koppen met h1, h2, h3 tags. 

- [x] Maak gebruik van beschrijvende kopteksten. 

- [x] Duidelijke benaming voor knoppen. 

- [x] Test zelf je code-kwaliteit via www.validator.w3.org  

- [x] Test je syntax. 

- [x] Maak niet alleen gebruik van kleuren om iets duidelijk te maken of uit te leggen maar ook van vormen.  

- [x] Inlaad snelheid zo hoog mogelijk. 

## Summary

### Description

- Nieuw overzicht voor de trainingpagina en de crud pagina daarvoor

### User story 

- Als websitebezoeker wil ik dat de data op de trainingspagina gemakkelijk te lezen is, zodat ik gemakkelijk kan opzoeken wanneer mijn training is

### List of acceptation criteria

- Tekst staat horizontaal.

- Het is duidelijk wanneer er geen training is.

- Het is duidelijk in welke groep je zit.

- de crud pagina bevat alleen toekomstige waarden

## Challenges and Solutions

### Challenge 1

- De navigatie van de weken was lastig om werkend te krijgen

### Solution 1

- koppijn

## User Interface

![image](https://github.com/Mees-H/SCRUM-SOp/assets/46578728/8c445a66-655a-4fc6-8cc1-4e3de0e40f28)
- Bovenwater view

![image](https://github.com/Mees-H/SCRUM-SOp/assets/46578728/eb5f23f8-a4c7-4d02-9b0b-488d4d2fb57d)
- Onderwater index view

2023-06-19 10:53 UTC, lauravdh1 commented
![image](https://github.com/Mees-H/SCRUM-SOp/assets/82824855/d301f9e4-5f58-42a5-828a-00a60f3fd342)
Lijkt me beter om 'H:i' formaat aan te houden voor de tijd

![image](https://github.com/Mees-H/SCRUM-SOp/assets/82824855/94ca1eda-0637-48d7-b2a7-217ed4eb297c)
Witte 'pijlen' in de knoppen zijn een beetje klein

2023-06-19 11:00 UTC, lauravdh1 commented on resources/views/training/index.blade.php
> +{{--                                <a href="{{ route('trainingsessions.edit',$session->Id)}}" class="btn btn-primary">Aanpassen</a>--}}
commentaar weg

2023-06-19 11:00 UTC, lauravdh1 commented on resources/views/training/index.blade.php
> +                        <td>tijd</td>
Tijd met hoofdletter

2023-06-19 11:00 UTC, lauravdh1 commented on resources/views/training/index.blade.php
> +                        <td>Actions</td>
Acties

2023-06-19 11:29 UTC, webwizard678 requested changes
paar kleine dingetjes

2023-06-19 11:29 UTC, webwizard678 commented on public/img/image1687169596.jpg
deze moet weg

2023-06-19 11:29 UTC, webwizard678 commented on resources/views/training/index.blade.php
misschien wat meer ruimte tussen 2 items zodat je weet welke tekst bij elkaar hoort

2023-06-21 17:35 UTC, Mees-H approved these changes

2023-06-21 20:42 UTC, lauravdh1 approved these changes

2023-06-22 07:05 UTC, webwizard678 approved these changes
lgtm

2023-06-22 07:08 UTC, merged