Detailspagina Evenementen
Mees-H/SCRUM-SOp pull request #25
Opened 2023-04-03 15:08 UTC by PerryWdm

# Pull request

- Evenementen

## Summary
Een detail paginas voor de evenementen aangemaakt

### Description

- Op de detailpagina worden verschillende gegevens getoond van het betreffende evenement

### User story 

- User story S8S-13: Als websitebezoeker wil ik de details van de evenementen kunnen bekijken, zodat ik weet waar ik aan toe ben als ik me in zou schrijven voor een evenement

### List of acceptation criteria

- Er staat een beschrijving bij elk evenementen.

- De exacte locaties van de evenementen worden vernoemd.

- De organisator wordt vernoemd.

- Er staan promotiefoto’s.

- De gegevens van het moment van het betreffende evenement staan hier vermeld (datum, tijd, ingedeelde personen per groep, etc.) (zie userstory “Als websitebezoeker wil ik een overzicht van evenementen bekijken..“)

## Challenges and Solutions

### Challenge 1

- Ik vond het lastig om een passende layout te maken bij de pagina

### Solution 1

- Ik heb inspiratie opgedaan van andere golfwebsites, waarna ik zelf een idee had

## User Interface

- 
![image](https://user-images.githubusercontent.com/101800635/229550851-ddd7ed2c-722f-4c34-a2d9-e6bd5ade6871.png)

## Checklist

- [x] All tests are passed.
- [x] Code compiles.
- [x] No errors in other parts of the program.
- [x] Code is commented on difficult parts.
- [x] All commits are clearly named.
- [x] Two people are mentioned to review this pull request
- [x] There is a clear description of the functionality and images are added for clarification.
- [x] Hours are registered in Clockify.
- [x] Coding standards have been adhered to.

2023-04-06 13:47 UTC, JoshavEngelen approved these changes
Als de dusk testen bij jou geen foutmeldingen geeft, is het prima

2023-04-07 15:05 UTC, Qoen1 requested changes

2023-04-07 15:05 UTC, Qoen1 commented on resources/views/evenement.blade.php
>                  <a href="/events/enroll/{{$post->id}}" class="btn-primary btn">Inschrijven</a>
![image](https://user-images.githubusercontent.com/90761435/230630668-f3b128db-014d-4faa-bc82-2470fae0ff1d.png)
ook hier te weinig contrast

2023-04-07 15:05 UTC, Qoen1 commented on resources/views/detailEvenement.blade.php
misschien ook bij deze pagina een inschrijf knop?

2023-04-07 15:05 UTC, Qoen1 commented on resources/views/events/index.blade.php
![image](https://user-images.githubusercontent.com/90761435/230631393-b5ba13cd-cc00-4ad2-b12a-cd30dc5afe5b.png)
ook hier ff naar de contrast kijken

2023-04-08 15:04 UTC, Qoen1 approved these changes
lgtm

2023-04-10 11:34 UTC, merged