Contactgegevens crud
Mees-H/SCRUM-SOp pull request #29
Opened 2023-04-08 15:11 UTC by EvaVanGurp

# Pull request

- Team

## Summary

### Description

- CRUD systeem voor het onderhouden van teamleden

### User story 

- Als websitebezoeker wil ik de contactgegevens van de werknemers kunnen zien, zodat ik weet wie ik kan aanspreken voor welke zaken en hoe ik deze persoon kan bereiken.

### List of acceptation criteria

- Er is een contactpagina.

- Er staan gegevens van de leden van het team.

o Naam

o Functie

o E-mail

o Mobiel telefoonnummer

## Challenges and Solutions

### Challenge 1

- Foto's uploaden

### Solution 1

- Een video tutorial gekeken

## User Interface

- ![image](https://user-images.githubusercontent.com/46578728/230728705-61e19917-0ca3-4802-aa24-0520c243863f.png)
Overzichtpagina
- ![image](https://user-images.githubusercontent.com/46578728/230728730-6b01df98-253e-48b0-9bd8-495270a955d9.png)
Index pagina
- ![image](https://user-images.githubusercontent.com/46578728/230728770-80c6e066-4df5-4498-90e4-edd8b4e762f6.png)
Edit pagina

## Checklist

- [x] All tests are passed.
- [x] Code compiles.
- [x] No errors in other parts of the program.
- [x] Code is commented on difficult parts.
- [x] All commits are clearly named.
- [x] Two people are mentioned to review this pull request
- [x] There is a clear description of the functionality and images are added for clarification.
- [x] Hours are registered in Clockify.
- [x] Coding standards have been adhered to.

2023-04-08 15:22 UTC, Mees-H requested changes
ziet er goed uit, alleen nog een opmerking over de logica in de views: als dat niet mogelijk is in de controller dan is het prima

2023-04-08 15:22 UTC, Mees-H commented on app/Http/Controllers/TeamController.php
> +            ['phonenumber.digits_between' => 'Telefoonnummer moet 10 cijfers zijn.']);
waarom is hier een tweede array geopend? idk of het functioneel uitmaakt

2023-04-08 15:22 UTC, Mees-H commented on app/Http/Controllers/TeamController.php
> +            ['phonenumber.digits_between' => 'Telefoonnummer moet 10 cijfers zijn.']);
oh wacht dit is de error message, prima

2023-04-08 15:22 UTC, Mees-H commented on resources/views/members/index.blade.php
> +                            @if($member->imgurl != '')
volgensmij kan je logica zoals dit beter afhandelen in de controller

2023-04-08 15:22 UTC, Mees-H commented on resources/views/members/team.blade.php
> +                        {{$member->name}}{{$member->function == '' ? '' : ' - '.$member->function}}<br>
dit is te veel logica voor de view

2023-04-09 11:51 UTC, webwizard678 approved these changes
lgtm

2023-04-11 17:25 UTC, Mees-H approved these changes
pico bello

2023-04-11 17:26 UTC, merged