feature/beperkingveld
Mees-H/SCRUM-SOp pull request #34
Opened 2023-04-13 12:24 UTC by webwizard678

# Pull request

- Geen epic

## Summary

### Description

- beperking veld in inschrijven voor evenement aangepast naar niet required en als naam spelershandicap

### User story 

- S8S-160 [1] Als websitebeheerder wil ik dat het beperking veld in het inschrijfformulier wordt gewijzigd, zodat de websitegebruikers een beperking niet negatief interpreteren

### List of acceptation criteria

- Het veld voor de beperking bij het inschrijfformulier voor een evenement moet gewijzigd worden naar Spelershandicap
- Het veld moet niet verplicht zijn

## Challenges and Solutions

### Challenge 1

- vinden waar de regel staat dat het veld verplicht is.

### Solution 1

- ctrl+f

## User Interface

![image](https://user-images.githubusercontent.com/103929586/231757215-737a7cfd-6d51-419f-b173-8bf8d3412888.png)

## Checklist

- [x] All tests are passed.
- [x] Code compiles.
- [x] No errors in other parts of the program.
- [x] Code is commented on difficult parts.
- [x] All commits are clearly named.
- [x] Two people are mentioned to review this pull request
- [x] There is a clear description of the functionality and images are added for clarification.
- [x] Hours are registered in Clockify.
- [x] Coding standards have been adhered to.

2023-04-18 09:58 UTC, ChendoMonster404 requested changes
nog even de benamingen aanpassen

2023-04-18 09:58 UTC, ChendoMonster404 commented on app/Http/Controllers/EventController.php
> +            ['name' => $request['name'], 'birthday' => $request['birthday'], 'email' => $request['email'], 'phonenumber' => $request['phonenumber'], 'address' => $request['address'], 'city' => $reque
maak van disability even handicap of golfhandicap. maakt het iets duidelijker

2023-04-18 09:58 UTC, ChendoMonster404 commented on app/Http/Controllers/EventController.php
> +            'disability' => 'max:255',
disability -> (golf)handicap

2023-04-18 09:58 UTC, ChendoMonster404 commented on app/Http/Requests/MailPostEventRequest.php
> +            'disability' => 'nullable|max:255',
same thing here

2023-04-18 09:58 UTC, ChendoMonster404 commented on app/Http/Requests/MailPostEventRequest.php
>              'disability.max' => 'De beschrijving van uw beperking mag niet langer zijn dan 255 karakters',
beperking -> (golf)handicap

2023-04-18 09:58 UTC, ChendoMonster404 commented on resources/views/events/aanmelden.blade.php
> +                            Spelershandicap
golf handicap

2023-04-19 13:09 UTC, PerryWdm approved these changes
Niets op aan te merken. Prima

2023-04-21 05:58 UTC, merged