chore(geslacht): added field for gender in mail and webpage enroll fo…
Mees-H/SCRUM-SOp pull request #35
Opened 2023-04-13 12:47 UTC by webwizard678

# Pull request

- Geen epic

## Summary

### Description

- Geslacht veld toegevoegd voor inschrijven voor een event. dit komt ook in de mail te staan.

### User story 

- S8S-203 [1] Als websitebeheerder wil ik dat er een invoerveld komt voor geslacht in het inschrijfformulier, zodat het duidelijker is met wie de organisatoren van een evenement te maken hebben

### List of acceptation criteria

- In het inschrijfformulier moet een tekstveld komen voor het geslacht van de betreffende persoon

## Challenges and Solutions

### Challenge 1

- nvt

### Solution 1

- nvt

## User Interface

![image](https://user-images.githubusercontent.com/103929586/231762971-7e2181b3-c827-4a01-9b83-742e4224a7b7.png)

![image](https://user-images.githubusercontent.com/103929586/231762890-8214d053-f9d7-4d94-9190-7582820f8f62.png)

## Checklist

- [ ] All tests are passed.
- [ ] Code compiles.
- [ ] No errors in other parts of the program.
- [ ] Code is commented on difficult parts.
- [ ] All commits are clearly named.
- [ ] Two people are mentioned to review this pull request
- [ ] There is a clear description of the functionality and images are added for clarification.
- [ ] Hours are registered in Clockify.
- [ ] Coding standards have been adhered to.

2023-04-18 09:53 UTC, ChendoMonster404 approved these changes
LGTM, ik weet alleen niet zeker of we het geslacht veld wel verplicht moeten maken maar is misschien toch wel beter

2023-04-19 13:14 UTC, Mees-H commented on resources/views/events/aanmelden.blade.php
> +                            <input type="text" class="form-control" id="gender"
Waarom is geslacht een tekstveld? Vgsm is het niet handig als iemand 'blabla' in kan typen. Dropdown lijkt me beter

2023-04-19 13:25 UTC, Mees-H commented on resources/views/events/aanmelden.blade.php
> +                            <span class="requiredStar">*</span>Geslacht
Er is een verschil tussen geslacht en gender, geslacht is biologisch en gender is waarmee je je identificeert. Omdat niet iedereen zich identificeert met zijn geslacht kan je hier beter naar de gender vragen

2023-04-19 13:29 UTC, Mees-H commented on resources/views/events/aanmelden.blade.php
> +                            <input type="text" class="form-control" id="gender"
nog een toevoeging met gender ipv geslacht: naar mijn mening zijn de 5 meest gebruikte genders voldoende om genoeg af te dekken. Andere opties kan je afdekken met 'anders'
![image](https://user-images.githubusercontent.com/103929631/233089510-298f3ac4-e792-40d5-a7da-f90ed2e87238.png)

2023-04-20 14:13 UTC, Mees-H requested changes
nog de ddd weghalen en dan kan die gemerged worden

2023-04-21 20:41 UTC, Mees-H approved these changes
Netjes!

2023-04-25 11:03 UTC, merged