Rooster crud
Mees-H/SCRUM-SOp pull request #37
Opened 2023-04-15 09:32 UTC by EvaVanGurp

# Pull request

- Oefensessies

## Summary

### Description

- CRUD functionality for the training sessions

### User story 

- Als websitebeheerder wil ik het rooster kunnen beheren, zodat de andere begeleiders/coaches en deelnemers op de hoogte zijn van de aangebrachte wijzigingen aan het rooster.

### List of acceptation criteria

- Het rooster kan gedeeld worden.

- Het rooster heeft CRUD eigenschappen
- Er kan een nieuw rooster toe worden gevoegd.
- Het rooster kan gewijzigd worden.
- Het rooster kan worden ingezien

- Er is zichtbaar wanneer de vakanties plaatsvinden.

## Challenges and Solutions

### Challenge 1

- Testing

### Solution 1

- Copied stuff from different testing files

## User Interface

- ![image](https://user-images.githubusercontent.com/46578728/232205657-bedc9993-0765-451d-b3e3-321224c47da1.png)
Index page
- ![image](https://user-images.githubusercontent.com/46578728/232205587-3ecf81b5-08ad-4ebb-bbf9-1ce1bfa07b10.png)
Create page
- ![image](https://user-images.githubusercontent.com/46578728/232205616-bfb025e7-1016-468b-b79a-485be79f34de.png)
Edit page

## Checklist

- [x] All tests are passed.
- [x] Code compiles.
- [x] No errors in other parts of the program.
- [x] Code is commented on difficult parts.
- [x] All commits are clearly named.
- [x] Two people are mentioned to review this pull request
- [x] There is a clear description of the functionality and images are added for clarification.
- [x] Hours are registered in Clockify.
- [x] Coding standards have been adhered to.

2023-04-15 10:04 UTC, ChendoMonster404 approved these changes
ziet er goed uit, heb niks om op te merken

2023-04-17 11:31 UTC, PerryWdm requested changes
Ziet er prima uit. Maar er zijn wel wat kleine aanpassingen nodig.

2023-04-17 11:31 UTC, PerryWdm commented on resources/views/training/index.blade.php
> +        <h1 class="display-3">Trainings</h1>
Misschien hier ook trainingen van maken als h1

2023-04-17 11:31 UTC, PerryWdm commented on resources/views/training/index.blade.php
> +                            <input type="checkbox" class="form-check-input" {{$session->IstrainingSession == 1 ? '' : 'checked'}} disabled/>
Opzich prima, maar ik denk dat het een beetje verwarrend is, om een input checkbox van te maken, want dan lijkt het alsof je het daar kan aanpassen. Misschien iets anders, zoals een vinkje oid.

2023-04-17 11:31 UTC, PerryWdm commented on app/Http/Controllers/TrainingController.php
> +        TrainingSession::find($id)->delete();
Hetzelfde als hierboven. Als ik veel op verwijderen druk, krijg ik namelijk een foutmelding

2023-04-17 11:31 UTC, PerryWdm commented on app/Http/Controllers/TrainingController.php
> +        $session = TrainingSession::findOrFail($id);
Wat als deze niet gevonden wordt? Try catch kan hier helpen

2023-04-17 11:31 UTC, PerryWdm commented on app/Http/Controllers/TrainingController.php
> +            'starttime' => 'required',
Op dit moment kan ik de eindtijd voor de starttijd doen. Ook bij het aanmaken van een nieuwe training

2023-04-17 11:31 UTC, PerryWdm commented on routes/web.php
> +Route::resource('trainingsessions', TrainingController::class);
Het onderhouden aan de adminrol toevoegen

2023-04-17 13:34 UTC, merged