Feature/create users
Mees-H/SCRUM-SOp pull request #39
Opened 2023-04-16 12:39 UTC by Qoen1

# Pull request

- Mention the epic here.

## Summary

### Description

- aanmak en verwijder functionaliteit van accounts voor beheerder

### User story 

- https://chendo.atlassian.net/browse/S8S-136

### List of acceptation criteria

ik kan begeleiders, coaches en admins aanmaken

begeleiders en coaches kunnen verwijderd worden d.m.v. een soft delete

deze functionaliteit is alleen beschikbaar voor de admin

admin kan niet verwijderd of toegevoegd worden.

registratie heeft de velden gebruikersnaam, wachtwoord en bevestig wachtwoord

## Challenges and Solutions

### Challenge 1

- geen

### Solution 1

- nvt

## User Interface
![image](https://user-images.githubusercontent.com/90761435/232311074-efe86d26-46a3-47f8-8107-8a9cb9d32fad.png)
![image](https://user-images.githubusercontent.com/90761435/232311285-60f8bc28-09a9-4f97-bb06-0cba2e23dce1.png)
![image](https://user-images.githubusercontent.com/90761435/232311710-30374026-a4f8-430a-a8d3-5c6e264a77ef.png)

## Checklist

- [x] All tests are passed.
- [x] Code compiles.
- [x] No errors in other parts of the program.
- [x] Code is commented on difficult parts.
- [x] All commits are clearly named.
- [x] Two people are mentioned to review this pull request
- [x] There is a clear description of the functionality and images are added for clarification.
- [x] Hours are registered in Clockify.
- [x] Coding standards have been adhered to.

2023-04-16 13:53 UTC, EvaVanGurp requested changes
Paar kleine opmerkingen, verder ziet het er goed uit

2023-04-16 13:53 UTC, EvaVanGurp commented on app/Http/Controllers/Admin/CreateUserController.php
> +        //ddd($request);
Haal dit er nog ff uit

2023-04-16 13:53 UTC, EvaVanGurp commented on app/Http/Controllers/Admin/CreateUserController.php
> +        return redirect('/admin/gebruikers')->with('success', 'Gebruiker aangemaakt!');
Een punt is hier beter dan een uitroepteken, dat is consistenter

2023-04-17 10:52 UTC, ChendoMonster404 requested changes
naast de feedback van Eva heb ik zelf een een opmerking gehad

2023-04-17 10:52 UTC, ChendoMonster404 commented on resources/views/admin/userlist.blade.php
> +            @endif
het zou er denk ik beter uitzoek als je hier een knop van maakt

2023-04-27 10:30 UTC, EvaVanGurp approved these changes
LGTM

2023-04-28 10:32 UTC, ChendoMonster404 approved these changes
Ziet er goed uit, geen commentaar verder

2023-04-28 10:36 UTC, merged