Feature/sitemap refactor
Mees-H/SCRUM-SOp pull request #42
Opened 2023-05-02 12:43 UTC by ChendoMonster404

# Pull request

nvt

## Summary

### Description

toegankelijk was niet helemaal top ivm geen alt tag. deze is nu toegevoegd aan iedere link

### User story 

S8S-257 Als websitebezoeker wil ik dat de sitemap toegankelijk is zodat ik optimaal wordt gesteund op de website

### List of acceptation criteria

Acceptatiecriteria:

Bij elke link staat een label die voorgelezen wordt door een screenreader in plaats van de link.

De label geeft een descriptieve betekenis aan de link waar het bij hoort

## Challenges and Solutions

### Challenge 1

vast gezeten doordat controller enigszins onduidelijk was 

### Solution 1

nvt

## User Interface

![image](https://user-images.githubusercontent.com/85230291/235668539-65828ec2-4c87-4684-af66-9af1ff453105.png)

## Checklist

- [x] All tests are passed.
- [x] Code compiles.
- [x] No errors in other parts of the program.
- [x] Code is commented on difficult parts.
- [x] All commits are clearly named.
- [x] Two people are mentioned to review this pull request
- [x] There is a clear description of the functionality and images are added for clarification.
- [x] Hours are registered in Clockify.
- [x] Coding standards have been adhered to.

2023-05-02 13:34 UTC, Mees-H requested changes
s.v.p. met dev laten mergen ipv main

2023-05-03 12:54 UTC, Qoen1 requested changes
niet naar main pushen

2023-05-03 12:55 UTC, Qoen1 approved these changes
lgtm

2023-05-03 13:35 UTC, Mees-H requested changes
Uitstekende oplossing voor de alt tags maar ik vind dat de benaming iets beter kan

2023-05-03 13:35 UTC, Mees-H commented on storage/app/public/sitemap.json
>                      "name": "home",
Lijkt me beter als dit een nederlandse benaming heeft zoals "startpagina" + met een hoofdletter begint

2023-05-03 13:35 UTC, Mees-H commented on storage/app/public/sitemap.json
>                      "name": "faq",
Verander naar "Veelgestelde Vragen"

2023-05-11 09:35 UTC, Mees-H requested changes
2 kleine typefouten en nog pullen van dev en dan kan die approved worden. stuur ff een berichtje op discord als het klaar is dan approve ik hem gelijk

2023-05-11 10:29 UTC, Mees-H approved these changes
LGTM

2023-05-11 10:56 UTC, merged