Edit galerij/backend
Mees-H/SCRUM-SOp pull request #62
Opened 2023-05-21 23:24 UTC by JoshavEngelen

# Definition of Done

## Functionele definities 

- [x] De acceptatiecriteria van de user story zijn gehaald. 

- [ ] Elk stuk werk is nagekeken door minimaal 2 andere programmeurs. 

- [x] Het programma wordt getest en werkt op 2 verschillende browsers (Google Chrome & Edge). 

### Toegankelijkheid 

- [ ] De website moet voor iedereen te navigeren zijn. 

- [ ] Inclusief mensen met een beperking. 

- [ ] De website dient volledig navigeerbaar te zijn zonder gebruik te maken van een muis. 

- [ ] Dit betekent navigeren via de tab en enter toets met behulp van spraak. 

- [ ] De knoppen zijn voorzien van duidelijke beschrijvingen. 

- [ ] De knoppen zijn groot genoeg om de tekst te bevatten. 

- [x] De teksten op de website bevatten geen spelfouten en zijn duidelijk geformuleerd. 

- [ ] Zorg voor voldoende contrast. 

- [ ] Contrast wordt getest met deze tool: https://webaim.org/resources/contrastchecker/  

- [ ] De WCAG AAA test moet pass teruggeven. 

- [x] Maak geen gebruik van hyperlinks met een klik hier maar gebruik een betekenisvolle beschrijving.  

Zoals: Lees meer over regulering. 

- [ ] Maak korte en inhoudelijke pagina’s. 

## Technische definities 

### Reviewers 

- [ ] Elke pull request is door minimaal 2 personen nagekeken. 

- [ ] Een taak wordt pas als af beschouwd zodra hij is goedgekeurd door de 2 reviewers en samengevoegd is op de juiste branch. 

- [ ] De reviewer doorloopt de happy flow. 

- [ ] Hierbij maakt de reviewer gebruik van de juiste werkwijze van de website. 

- [ ] De reviewer probeert d.m.v. onjuist gebruik van de website de website te breken. 

- [ ] Dit kan hij/zij doen door verkeerde invoer van velden. 

- [ ] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

### Ontwikkelaar 

- [ ] Er is geen SQL injection mogelijk  

- [ ] Alle invoervelden zijn voorzien van een regex. 

- [ ] Deze regex zorgt ervoor dat alleen het noodzakelijke ingevoerd kan worden. 

- [x] De coding guidlines zijn aangehouden. 

- [x] De geschreven code compileert. 

- [x] De geschreven code veroorzaakt geen crashes. 

- [x] Code levert geen complicaties op met de AVG-wetgeving. 

- [ ] Dusk tests worden geschreven voor de happy flow en minimaal 1 bad flow. 

- [ ] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

- [ ] De siteMap en navigatiebalk zijn geüpdatet op basis van de aanpassingen. 

### Toegankelijkheid 

- [ ] Houd je aan de standaarden voor het web. 

- [ ] De website moet door gebruik van tab te navigeren zijn. 

- [ ] Voeg een alt-tekst toe bij niet-tekstuele-content met betekenisvolle informatie. 

- [ ] Maak geen gebruik van spaties. 

- [ ] De knoppen hebben een minimaal formaat van 21x30px. 

- [ ] Maak gebruik van een rustige layout. 

- [ ] Maak gebruik van koppen met h1, h2, h3 tags. 

- [ ] Maak gebruik van beschrijvende kopteksten. 

- [ ] Duidelijke benaming voor knoppen. 

- [ ] Test zelf je code-kwaliteit via www.validator.w3.org  

- [ ] Test je syntax. 

- [ ] Maak niet alleen gebruik van kleuren om iets duidelijk te maken of uit te leggen maar ook van vormen.  

- [ ] Inlaad snelheid zo hoog mogelijk. 

## Summary

### Description

- De albums zijn te wijzigen. Dit houdt in: de datum, beschrijving en de foto's kunnen gewijzigd worden. Door middel van checkboxes kun je meerdere foto's tegelijk verwijderen. Door de knop "Foto's toevoegen" kun je meerdere foto's uploaden die je in het album wilt hebben.

### User story 

- Als websitebeheerder wil ik fotoalbums kunnen wijzigen, zodat de gewenste foto’s zichtbaar worden voor de websitebezoeker

### List of acceptation criteria

- De opties zijn om foto’s te verwijderen van het album, of toe te voegen.

- Wijzig optie door middel van een knop

- Meerdere foto’s selecteren om te verwijderen

- Verwijder- en toevoegknop is beschikbaar

## Challenges and Solutions

### Challenge 1

- Ik liep er tegenaan dat ik niet helemaal wist hoe ik geuploade foto's kon valideren

### Solution 1

- Ik heb hier met Koen voor gezeten en zijn er achter gekomen dat het in feite vrij simpel is
![image](https://github.com/Mees-H/SCRUM-SOp/assets/103433509/6ca4b7d6-4a0a-4ae1-9bec-5825392fa867)

## User Interface

![image](https://github.com/Mees-H/SCRUM-SOp/assets/103433509/537b8d70-a0c6-490c-b208-9f42600505be)
Lees de eerder geschreven Description voor context

2023-05-23 08:42 UTC, Mees-H requested changes

2023-05-23 08:42 UTC, Mees-H commented on app/Http/Controllers/GalleryController.php
Let de volgende keer op de benaming van je branch

2023-05-23 08:42 UTC, Mees-H commented on app/Http/Controllers/GalleryController.php
> +                return response()->json(['error' => 'The image is not a file'], 400);
als je niks uploadt krijg je geen error message

2023-05-23 08:42 UTC, Mees-H commented on app/Http/Controllers/GalleryController.php
> +            return redirect('/galerij')->with('success', 'Afbeeldingen zijn verwijderd uit album');
waarom ga ik terug naar de galerij als ik foto's verwijder? mij lijkt het handiger om bij dat album te blijven

2023-05-23 08:42 UTC, Mees-H commented on config/filesystems.php
> +            'driver' => 'local',
gaat dit problemen opleveren op de live server?

2023-05-23 08:42 UTC, Mees-H commented on resources/views/gallery/edit.blade.php
> +                <button type="submit" form="updateAlbum" class="btn btn-primary wide-button">Update</button>
Ik vind deze update knop niet zo handig in combinatie met foto's toevoegen. De functionaliteit van foto's toevoegen staat in principe los van de albumvelden aanpassen. Miss de upload afbeelingen knop ook op de CRUD pagina zetten?

2023-05-23 08:42 UTC, Mees-H commented on resources/views/gallery/edit.blade.php
> +                <form method="post" id="updateAlbum" action="{{ route('galerij.update', $album->id) }}">
het aanpassen van de CRUD data wordt onthouden als je een foto uploadt maar niet in de DB

2023-05-23 08:42 UTC, Mees-H commented on resources/views/gallery/edit.blade.php
> +                            <button onclick="selectPicture(this)" class='delete-button'></button>
Hoe toegankelijk is het voor screenreaders om deze knoppen te lezen?

2023-05-23 08:42 UTC, Mees-H commented on resources/views/gallery/edit.blade.php
> +                            <button onclick="selectPicture(this)" class='delete-button'></button>
ook is een meerdere selectie veld niet handig omdat je niet precies weet wanneer iets verwijderd is, te veel stappen imo

2023-05-23 08:42 UTC, Mees-H commented on resources/views/components/album-upload-form.blade.php
> +<form class="col-md-6 image-uplode d-inline-block border shadow-lg rounded p-2 mt-5" action="{{ $action }}" method="POST" enctype="multipart/form-data">
![image](https://github.com/Mees-H/SCRUM-SOp/assets/103929631/67f20c43-2bda-43d7-8a73-a7bd6f434f3e)

2023-05-23 09:58 UTC, Qoen1 commented
![image](https://github.com/Mees-H/SCRUM-SOp/assets/90761435/9385c9d5-d5d2-4948-896c-e89c4fd36f09)
bij mij werkt de styling niet goed

2023-05-23 09:59 UTC, Qoen1 commented
en ik krijg errors
![image](https://github.com/Mees-H/SCRUM-SOp/assets/90761435/75f30f4a-7e99-4f75-8059-2931a08ff219)

2023-05-24 15:12 UTC, Qoen1 requested changes
meerdere foto's toevoegen werkt niet. hij blijft ook op dezelfde pagina dus denk dat het niet door de validatie heenkomt.

Foto's worden niet verwijderd als je op de delete knop drukt (ja wel uit de db maar niet uit de bestanden)

als ik een album verwijder worden de Foto's niet eens uit de db gehaald.

ik zie geen error meldingen bij het uploaden van files (als ik bijv een pdf upload of helemaal niks)

als ik een foto toevoeg denk ik dat je beter terug kan gaan naar de edit album page ipv het overzicht.

2023-05-27 16:30 UTC, Mees-H approved these changes
LGTM

2023-05-28 12:08 UTC, Qoen1 requested changes
paar kleine dingen

2023-05-28 12:08 UTC, Qoen1 commented on app/Http/Controllers/GalleryController.php
> +        if (!isset($request->images)) {
moet de validatie niet eerst?

2023-05-28 12:08 UTC, Qoen1 commented on routes/web.php
> +    // Route::get('/galerij/{year}', [GalleryController::class, 'showGallery'])->name('galerij_jaar');
dit mag weg

2023-05-31 10:55 UTC, Qoen1 approved these changes

2023-05-31 10:56 UTC, merged