Feature/technical dept
Mees-H/SCRUM-SOp pull request #63
Opened 2023-05-23 15:42 UTC by PerryWdm

# Definition of Done

## Functionele definities 

- [X] De acceptatiecriteria van de user story zijn gehaald. 

- [ ] Elk stuk werk is nagekeken door minimaal 2 andere programmeurs. 

- [X] Het programma wordt getest en werkt op 2 verschillende browsers (Google Chrome & Edge). 

### Toegankelijkheid 

- [X] De website moet voor iedereen te navigeren zijn. 

- [X] Inclusief mensen met een beperking. 

- [X] De website dient volledig navigeerbaar te zijn zonder gebruik te maken van een muis. 

- [X] Dit betekent navigeren via de tab en enter toets met behulp van spraak. 

- [X] De knoppen zijn voorzien van duidelijke beschrijvingen. 

- [X] De knoppen zijn groot genoeg om de tekst te bevatten. 

- [X] De teksten op de website bevatten geen spelfouten en zijn duidelijk geformuleerd. 

- [X] Zorg voor voldoende contrast. 

- [X] Contrast wordt getest met deze tool: https://webaim.org/resources/contrastchecker/  

- [X] De WCAG AAA test moet pass teruggeven. 

- [X] Maak geen gebruik van hyperlinks met een klik hier maar gebruik een betekenisvolle beschrijving.  

Zoals: Lees meer over regulering. 

- [X] Maak korte en inhoudelijke pagina’s. 

## Technische definities 

### Reviewers 

- [ ] Elke pull request is door minimaal 2 personen nagekeken. 

- [ ] Een taak wordt pas als af beschouwd zodra hij is goedgekeurd door de 2 reviewers en samengevoegd is op de juiste branch. 

- [ ] De reviewer doorloopt de happy flow. 

- [ ] Hierbij maakt de reviewer gebruik van de juiste werkwijze van de website. 

- [ ] De reviewer probeert d.m.v. onjuist gebruik van de website de website te breken. 

- [ ] Dit kan hij/zij doen door verkeerde invoer van velden. 

- [ ] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

### Ontwikkelaar 

- [X] Er is geen SQL injection mogelijk  

- [X] Alle invoervelden zijn voorzien van een regex. 

- [X] Deze regex zorgt ervoor dat alleen het noodzakelijke ingevoerd kan worden. 

- [X] De coding guidlines zijn aangehouden. 

- [X] De geschreven code compileert. 

- [X] De geschreven code veroorzaakt geen crashes. 

- [X] Code levert geen complicaties op met de AVG-wetgeving. 

- [] Dusk tests worden geschreven voor de happy flow en minimaal 1 bad flow. 

- [X] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

- [X] De siteMap en navigatiebalk zijn geüpdatet op basis van de aanpassingen. 

### Toegankelijkheid 

- [X] Houd je aan de standaarden voor het web. 

- [X] De website moet door gebruik van tab te navigeren zijn. 

- [X] Voeg een alt-tekst toe bij niet-tekstuele-content met betekenisvolle informatie. 

- [X] Maak geen gebruik van spaties. 

- [X] De knoppen hebben een minimaal formaat van 21x30px. 

- [X] Maak gebruik van een rustige layout. 

- [x] Maak gebruik van koppen met h1, h2, h3 tags. 

- [X] Maak gebruik van beschrijvende kopteksten. 

- [X] Duidelijke benaming voor knoppen. 

- [X] Test zelf je code-kwaliteit via www.validator.w3.org  

- [X] Test je syntax. 

- [X] Maak niet alleen gebruik van kleuren om iets duidelijk te maken of uit te leggen maar ook van vormen.  

- [X] Inlaad snelheid zo hoog mogelijk. 

## Summary
De oplossingen van allerlei technische achterstands problemen
### Description

- Navbar/dropdown update
- responsiveness
- slider fix
-  directories fix
- date format consistentie

### User story 

- Technical debt | User story 371

### List of acceptation criteria

- none

## Challenges and Solutions

### Challenge 1

- iedereen zijn eigen invulling

### Solution 1

- 

## User Interface

-

2023-05-24 15:34 UTC, Qoen1 requested changes
misschien kut dat ik dit nu opbreng maar als je in de slider een foto verwijderd wordt deze niet echt verwijderd maar alleen uit de db gehaald.

het trainingen schema heeft nu wel heel veel padding ineens, zit daar misschien ergens een enter of extra spatie verstopt? 

niet alle dusk tests slagen (nee ik heb het niet over de error waar ik mee bezig ben)

2023-05-24 18:14 UTC, webwizard678 requested changes
een hoop pagina's zijn nog niet responsive. Ook is er nog een test afbeelding die niet in de seeddata staat waardoor deze niet gebruikt wordt en dus weg mag

2023-05-24 18:14 UTC, webwizard678 commented on resources/views/layouts/Admin_navbar/admin_mobile_navbar.blade.php
> +                <ul class="border border-dark rounded d-none" id="content">
De search bar ziet er erg klein uit op mobile

2023-05-24 18:14 UTC, webwizard678 commented on resources/views/faq/index.blade.php
Deze pagina is niet responsive voor mobile

2023-05-24 18:14 UTC, webwizard678 commented on resources/views/gallery/index.blade.php
deze pagina is niet responsive,
haal bv id weg
zet knoppen onder elkaar.

2023-05-24 18:14 UTC, webwizard678 commented on resources/views/training/index.blade.php
deze pagina is niet responsive op mobiel,
zet knoppen onder elkaar,
haal id weg

2023-05-24 18:14 UTC, webwizard678 commented on resources/views/events/index.blade.php
deze pagina is niet responsive

2023-05-24 18:14 UTC, webwizard678 commented on public/img/golfclub_slider1684584431.jpg
Dit bestand mag weg aangezien dit niet gebruikt wordt.

2023-05-25 12:09 UTC, ChendoMonster404 commented on resources/views/events/index.blade.php
fixed

2023-05-25 12:09 UTC, ChendoMonster404 commented on resources/views/faq/index.blade.php
fixed

2023-05-26 10:24 UTC, webwizard678 requested changes
nog een klein verbeterpuntje

2023-05-26 10:24 UTC, webwizard678 commented on resources/views/events/index.blade.php
Het is een stuk verbeterd nu, Het is nog niet helemaal goed. Je kunt horizontaal scrollen terwijl dit eigenlijk niet de bedoeling is.

2023-05-26 20:22 UTC, Qoen1 requested changes
dusk tests slagen niet (zie thread)

2023-05-27 14:14 UTC, webwizard678 commented on resources/views/events/index.blade.php
goed verbeterd

2023-05-27 14:23 UTC, webwizard678 approved these changes
als de dusk tests gefixed zijn ziet het er goed uit

2023-05-31 11:03 UTC, Qoen1 approved these changes
nu slagen de tests wel

2023-05-31 19:39 UTC, Qoen1 requested changes
alles is kut

2023-05-31 21:08 UTC, Qoen1 approved these changes

2023-06-01 11:08 UTC, merged