Feature/privacy
Mees-H/SCRUM-SOp pull request #71
Opened 2023-05-31 19:54 UTC by Qoen1

# Definition of Done

## Functionele definities 

- [ ] De acceptatiecriteria van de user story zijn gehaald. 

- [ ] Elk stuk werk is nagekeken door minimaal 2 andere programmeurs. 

- [ ] Het programma wordt getest en werkt op 2 verschillende browsers (Google Chrome & Edge). 

### Toegankelijkheid 

- [ ] De website moet voor iedereen te navigeren zijn. 

- [ ] Inclusief mensen met een beperking. 

- [ ] De website dient volledig navigeerbaar te zijn zonder gebruik te maken van een muis. 

- [ ] Dit betekent navigeren via de tab en enter toets met behulp van spraak. 

- [ ] De knoppen zijn voorzien van duidelijke beschrijvingen. 

- [ ] De knoppen zijn groot genoeg om de tekst te bevatten. 

- [ ] De teksten op de website bevatten geen spelfouten en zijn duidelijk geformuleerd. 

- [ ] Zorg voor voldoende contrast. 

- [ ] Contrast wordt getest met deze tool: https://webaim.org/resources/contrastchecker/  

- [ ] De WCAG AAA test moet pass teruggeven. 

- [ ] Maak geen gebruik van hyperlinks met een klik hier maar gebruik een betekenisvolle beschrijving.  

Zoals: Lees meer over regulering. 

- [ ] Maak korte en inhoudelijke pagina’s. 

## Technische definities 

### Reviewers 

- [ ] Elke pull request is door minimaal 2 personen nagekeken. 

- [ ] Een taak wordt pas als af beschouwd zodra hij is goedgekeurd door de 2 reviewers en samengevoegd is op de juiste branch. 

- [ ] De reviewer doorloopt de happy flow. 

- [ ] Hierbij maakt de reviewer gebruik van de juiste werkwijze van de website. 

- [ ] De reviewer probeert d.m.v. onjuist gebruik van de website de website te breken. 

- [ ] Dit kan hij/zij doen door verkeerde invoer van velden. 

- [ ] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

### Ontwikkelaar 

- [ ] Er is geen SQL injection mogelijk  

- [ ] Alle invoervelden zijn voorzien van een regex. 

- [ ] Deze regex zorgt ervoor dat alleen het noodzakelijke ingevoerd kan worden. 

- [ ] De coding guidlines zijn aangehouden. 

- [ ] De geschreven code compileert. 

- [ ] De geschreven code veroorzaakt geen crashes. 

- [ ] Code levert geen complicaties op met de AVG-wetgeving. 

- [ ] Dusk tests worden geschreven voor de happy flow en minimaal 1 bad flow. 

- [ ] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

- [ ] De siteMap en navigatiebalk zijn geüpdatet op basis van de aanpassingen. 

### Toegankelijkheid 

- [ ] Houd je aan de standaarden voor het web. 

- [ ] De website moet door gebruik van tab te navigeren zijn. 

- [ ] Voeg een alt-tekst toe bij niet-tekstuele-content met betekenisvolle informatie. 

- [ ] Maak geen gebruik van spaties. 

- [ ] De knoppen hebben een minimaal formaat van 21x30px. 

- [ ] Maak gebruik van een rustige layout. 

- [ ] Maak gebruik van koppen met h1, h2, h3 tags. 

- [ ] Maak gebruik van beschrijvende kopteksten. 

- [ ] Duidelijke benaming voor knoppen. 

- [ ] Test zelf je code-kwaliteit via www.validator.w3.org  

- [ ] Test je syntax. 

- [ ] Maak niet alleen gebruik van kleuren om iets duidelijk te maken of uit te leggen maar ook van vormen.  

- [ ] Inlaad snelheid zo hoog mogelijk. 

## Summary

### Description

- mooe privacy verklaring

### User story 

-  US 385

### List of acceptation criteria

-     Er is een nieuwe pagina met de privacyverklaring van de huidige website

    De privacyverklaring wordt in pdf formaat opgeslagen en geupload

    Elke keer als een pdf geupload wordt, wordt de vorige pdf overschreven

    De websitebeheerder heeft een pagina om de pdf’s te uploaden

## Challenges and Solutions

### Challenge 1

-  niks, ik ben geweldig

### Solution 1

- door geweldig te zijn

## User Interface

- (Image screenshot of UI with description here)
![image](https://github.com/Mees-H/SCRUM-SOp/assets/90761435/acd594e6-3c18-42e4-b997-68bd3d1e7ae5)
![image](https://github.com/Mees-H/SCRUM-SOp/assets/90761435/8c047a25-40c6-4f2d-8fa6-1cd2eba63275)

2023-05-31 20:46 UTC, JoshavEngelen requested changes
Nog ff een paar dingen fixen en dan is 't gtg

2023-05-31 20:46 UTC, JoshavEngelen commented on resources/views/layouts/layout.blade.php
> +                        <a class="nav-link text-dark dropdown-item {{ (request()->segment(1) == 'privacy') ? 'font-weight-bold' : '' }}" href="/privacy/edit">privacy</a>
Hoofdletter P >_>

2023-05-31 20:46 UTC, JoshavEngelen commented on app/Http/Controllers/PrivacyController.php
> +            //return view with errors
Comment kan weg. Lijkt me

2023-05-31 20:46 UTC, JoshavEngelen commented on app/Http/Controllers/PrivacyController.php
> +        }else{
Else is niet nodig

2023-05-31 20:46 UTC, JoshavEngelen commented on app/Http/Controllers/PrivacyController.php
> +        }else{
Deze kan ook weg

2023-05-31 22:13 UTC, EvaVanGurp approved these changes
LGTM

2023-06-01 18:32 UTC, JoshavEngelen approved these changes

2023-06-01 18:32 UTC, JoshavEngelen commented on app/Http/Controllers/PrivacyController.php
> +            $carousel= slider::create([
Volgens mij, is dit niet precies wat je wil doen

2023-06-01 19:08 UTC, JoshavEngelen commented on app/Http/Controllers/PrivacyController.php
> +            $carousel= slider::create([
Heb het zelf al verwijderd. Je kunt t mergen

2023-06-01 21:04 UTC, merged