added example
Mees-H/SCRUM-SOp pull request #72
Opened 2023-06-01 12:34 UTC by Qoen1

.env.example toegevoegd en onnodige regels weggelaten

2023-06-09 09:56 UTC, EvaVanGurp requested changes

2023-06-09 09:56 UTC, EvaVanGurp commented on .env.example
> +DB_PASSWORD=
Hier nog ff wat standaard waarden toevoegen ("SpecialGolf" bij database, "root" bij username, en mailer data)

2023-06-10 15:26 UTC, PerryWdm approved these changes
LGTM, mits je de feedback van Eva verwerkt

2023-06-13 10:31 UTC, EvaVanGurp approved these changes
LGTM

2023-06-13 11:06 UTC, merged