Fixed the bug for uploading images at the team page
Mees-H/SCRUM-SOp pull request #78
Opened 2023-06-06 10:03 UTC by PerryWdm

# Definition of Done

## Functionele definities 

- [X] De acceptatiecriteria van de user story zijn gehaald. 

- [ ] Elk stuk werk is nagekeken door minimaal 2 andere programmeurs. 

- [X] Het programma wordt getest en werkt op 2 verschillende browsers (Google Chrome & Edge). 

### Toegankelijkheid 

- [X] De website moet voor iedereen te navigeren zijn. 

- [X] Inclusief mensen met een beperking. 

- [X] De website dient volledig navigeerbaar te zijn zonder gebruik te maken van een muis. 

- [X] Dit betekent navigeren via de tab en enter toets met behulp van spraak. 

- [X] De knoppen zijn voorzien van duidelijke beschrijvingen. 

- [X] De knoppen zijn groot genoeg om de tekst te bevatten. 

- [X] De teksten op de website bevatten geen spelfouten en zijn duidelijk geformuleerd. 

- [X] Zorg voor voldoende contrast. 

- [X] Contrast wordt getest met deze tool: https://webaim.org/resources/contrastchecker/  

- [x] De WCAG AAA test moet pass teruggeven. 

- [X] Maak geen gebruik van hyperlinks met een klik hier maar gebruik een betekenisvolle beschrijving.  

Zoals: Lees meer over regulering. 

- [X] Maak korte en inhoudelijke pagina’s. 

## Technische definities 

### Reviewers 

- [ ] Elke pull request is door minimaal 2 personen nagekeken. 

- [ ] Een taak wordt pas als af beschouwd zodra hij is goedgekeurd door de 2 reviewers en samengevoegd is op de juiste branch. 

- [ ] De reviewer doorloopt de happy flow. 

- [ ] Hierbij maakt de reviewer gebruik van de juiste werkwijze van de website. 

- [ ] De reviewer probeert d.m.v. onjuist gebruik van de website de website te breken. 

- [ ] Dit kan hij/zij doen door verkeerde invoer van velden. 

- [ ] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

### Ontwikkelaar 

- [X] Er is geen SQL injection mogelijk  

- [X] Alle invoervelden zijn voorzien van een regex. 

- [X] Deze regex zorgt ervoor dat alleen het noodzakelijke ingevoerd kan worden. 

- [x] De coding guidlines zijn aangehouden. 

- [x] De geschreven code compileert. 

- [x] De geschreven code veroorzaakt geen crashes. 

- [x] Code levert geen complicaties op met de AVG-wetgeving. 

- [x] Dusk tests worden geschreven voor de happy flow en minimaal 1 bad flow. 

- [x] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

- [X] De siteMap en navigatiebalk zijn geüpdatet op basis van de aanpassingen. 

### Toegankelijkheid 

- [X] Houd je aan de standaarden voor het web. 

- [X] De website moet door gebruik van tab te navigeren zijn. 

- [X] Voeg een alt-tekst toe bij niet-tekstuele-content met betekenisvolle informatie. 

- [x] Maak geen gebruik van spaties. 

- [x] De knoppen hebben een minimaal formaat van 21x30px. 

- [X] Maak gebruik van een rustige layout. 

- [x] Maak gebruik van koppen met h1, h2, h3 tags. 

- [x] Maak gebruik van beschrijvende kopteksten. 

- [x] Duidelijke benaming voor knoppen. 

- [x] Test zelf je code-kwaliteit via www.validator.w3.org  

- [x] Test je syntax. 

- [x] Maak niet alleen gebruik van kleuren om iets duidelijk te maken of uit te leggen maar ook van vormen.  

- [X] Inlaad snelheid zo hoog mogelijk. 

## Summary
Bug Fix for uploading images at the team page

### Description
The images upload now at the right directory of the application

### User story 

- S8S 409 Als websitebeheerder wil ik dat het uploaden van foto's op de teampagina de betreffende foto ook weergeeft op de teampagina, zodat die te zien is

### List of acceptation criteria

- Het uploaden van een foto bij het toevoegen van een teamlid slaat het op in de applicatie en geeft het weer op de teampagina

## Challenges and Solutions
nvt
### Challenge 1

-nvt

### Solution 1

- nvt

## User Interface

- nvt

2023-06-06 10:20 UTC, EvaVanGurp approved these changes
LGTM

2023-06-06 10:44 UTC, Mees-H requested changes
Nog 3 dingen: 
Bij het aanpassen van een teamlid heeft het 'name' input field geen label
en
Omdat er 2x een layout op de pagina staat komt het id 'burger_menu_icon' 2x voor
en
Doe een CTRL+SHIFT+F op 'aria-expanded="false"', dit attribuut doet niks en levert errors op voor de devtools

2023-06-06 10:44 UTC, Mees-H commented on app/Http/Controllers/TeamController.php
Bij de store functie is het groups veld verplicht, terwijl dit bij de update functie niet geldt. Dit betekent dat je alle groepen van een gebruiker weg kan halen terwijl er een sterretje bij staat, want niet de bedoeling is

2023-06-06 10:44 UTC, Mees-H commented on app/Http/Controllers/TeamController.php
Als er een oude image is wordt die niet verwijderd uit het filesysteem

2023-06-06 10:44 UTC, Mees-H commented on app/Http/Controllers/TeamController.php
Error message van groups required is nog niet in het nederlands

2023-06-06 10:44 UTC, Mees-H commented on app/Http/Controllers/TeamController.php
Het verwijderen van een teamlid verwijdert de image niet uit het systeem

2023-06-06 10:44 UTC, Mees-H commented on resources/views/members/index.blade.php
> +                            <a href="{{ route('members.edit',$member->id)}}" class="btn btn-primary">Aanpassen</a>
Alle a tags op deze pagina voldoen niet aan de contrastcriteria

2023-06-06 10:44 UTC, Mees-H commented on resources/views/members/index.blade.php
> +                            <a href="{{ route('members.edit',$member->id)}}" class="btn btn-primary">Aanpassen</a>
DIt geldt ook voor de pagina's van het toevoegen en aanpassen van teamleden

2023-06-06 14:55 UTC, PerryWdm commented on resources/views/members/index.blade.php
> +                            <a href="{{ route('members.edit',$member->id)}}" class="btn btn-primary">Aanpassen</a>
Dit wordt in een andere user story opgepakt

2023-06-07 08:07 UTC, Mees-H requested changes
Als een foto te breed is dan overlapt het de tekst ernaast

2023-06-07 08:07 UTC, Mees-H commented on app/Http/Controllers/TeamController.php
> +                File::delete(public_path('img\\'.$image));
Dit verwijdert de image niet uit het systeem

2023-06-07 08:07 UTC, Mees-H commented on app/Http/Controllers/TeamController.php
> -            'phonenumber' => 'nullable|numeric|digits_between:10,10'
Het aanpassen van een teamlid verwijdert de foto als je iets anders aanpast, lijkt me niet handig, en hoef je ook niet op te lossen maar ik wil het wel aankaarten

2023-06-07 08:07 UTC, Mees-H commented on app/Http/Controllers/TeamController.php
> +                File::delete(public_path('img\\'.$image));
Bij het aanpassen wordt die wel goed verwijderd trouwens

2023-06-12 07:49 UTC, Mees-H approved these changes

2023-06-12 08:01 UTC, merged