Feature/training groep crud
Mees-H/SCRUM-SOp pull request #79
Opened 2023-06-06 10:15 UTC by EvaVanGurp

# Definition of Done

## Functionele definities 

- [x] De acceptatiecriteria van de user story zijn gehaald. 

- [ ] Elk stuk werk is nagekeken door minimaal 2 andere programmeurs. 

- [x] Het programma wordt getest en werkt op 2 verschillende browsers (Google Chrome & Edge). 

### Toegankelijkheid 

- [x] De website moet voor iedereen te navigeren zijn. 

- [x] Inclusief mensen met een beperking. 

- [x] De website dient volledig navigeerbaar te zijn zonder gebruik te maken van een muis. 

- [x] Dit betekent navigeren via de tab en enter toets met behulp van spraak. 

- [x] De knoppen zijn voorzien van duidelijke beschrijvingen. 

- [x] De knoppen zijn groot genoeg om de tekst te bevatten. 

- [x] De teksten op de website bevatten geen spelfouten en zijn duidelijk geformuleerd. 

- [x] Zorg voor voldoende contrast. 

- [x] Contrast wordt getest met deze tool: https://webaim.org/resources/contrastchecker/  

- [x] De WCAG AAA test moet pass teruggeven. 

- [x] Maak geen gebruik van hyperlinks met een klik hier maar gebruik een betekenisvolle beschrijving.  

Zoals: Lees meer over regulering. 

- [x] Maak korte en inhoudelijke pagina’s. 

## Technische definities 

### Reviewers 

- [ ] Elke pull request is door minimaal 2 personen nagekeken. 

- [ ] Een taak wordt pas als af beschouwd zodra hij is goedgekeurd door de 2 reviewers en samengevoegd is op de juiste branch. 

- [ ] De reviewer doorloopt de happy flow. 

- [ ] Hierbij maakt de reviewer gebruik van de juiste werkwijze van de website. 

- [ ] De reviewer probeert d.m.v. onjuist gebruik van de website de website te breken. 

- [ ] Dit kan hij/zij doen door verkeerde invoer van velden. 

- [ ] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

### Ontwikkelaar 

- [x] Er is geen SQL injection mogelijk  

- [ ] Alle invoervelden zijn voorzien van een regex. 

- [ ] Deze regex zorgt ervoor dat alleen het noodzakelijke ingevoerd kan worden. 

- [x] De coding guidlines zijn aangehouden. 

- [x] De geschreven code compileert. 

- [x] De geschreven code veroorzaakt geen crashes. 

- [x] Code levert geen complicaties op met de AVG-wetgeving. 

- [ ] Dusk tests worden geschreven voor de happy flow en minimaal 1 bad flow. 

- [x] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

- [x] De siteMap en navigatiebalk zijn geüpdatet op basis van de aanpassingen. 

### Toegankelijkheid 

- [x] Houd je aan de standaarden voor het web. 

- [x] De website moet door gebruik van tab te navigeren zijn. 

- [x] Voeg een alt-tekst toe bij niet-tekstuele-content met betekenisvolle informatie. 

- [x] Maak geen gebruik van spaties. 

- [x] De knoppen hebben een minimaal formaat van 21x30px. 

- [x] Maak gebruik van een rustige layout. 

- [x] Maak gebruik van koppen met h1, h2, h3 tags. 

- [x] Maak gebruik van beschrijvende kopteksten. 

- [x] Duidelijke benaming voor knoppen. 

- [x] Test zelf je code-kwaliteit via www.validator.w3.org  

- [x] Test je syntax. 

- [x] Maak niet alleen gebruik van kleuren om iets duidelijk te maken of uit te leggen maar ook van vormen.  

- [x] Inlaad snelheid zo hoog mogelijk. 

## Summary

### Description

- CRUD functionaliteit voor de traininggroepen

### User story 

- Als websitebeheerder wil ik groepen kunnen beheren, zodat ik kan zien welke deelnemers van de oefensessies in welke groep zitten en dit kan wijzigen naar wens.

### List of acceptation criteria

- Er kunnen groepen toegevoegd worden. 

- Er kunnen leden toegevoegd en verwijderd worden van de groepen

- Er kunnen groepen worden verwijderd

## Challenges and Solutions

### Challenge 1

- Het bugfixen van het refactoren van database fields

### Solution 1

- ctrl + F

## User Interface

![image](https://github.com/Mees-H/SCRUM-SOp/assets/46578728/1ddc7209-f577-4fef-9465-ec3d2a40bd54)
- Index pagina

![image](https://github.com/Mees-H/SCRUM-SOp/assets/46578728/f804ff3f-f9f8-4d5c-974f-0e8815f454bd)
- Persoon toevoegen pagina

2023-06-08 09:11 UTC, webwizard678 requested changes
klein foutje bij formulier. zo opgelost

2023-06-08 09:11 UTC, webwizard678 commented on resources/views/traininggroups/participant-create.blade.php
> +            </form>
de oude waardes worden niet onthouden als je iets verkeerd invult.

2023-06-14 19:02 UTC, webwizard678 requested changes
voor de gebruiker is niet te zien welke groep welk rooster heeft (er staat geen groepsnummer bij).

2023-06-19 08:46 UTC, webwizard678 approved these changes
lgtm

2023-06-19 09:32 UTC, ChendoMonster404 requested changes
factory verwijderen en dan approve ik de pr

2023-06-19 09:32 UTC, ChendoMonster404 commented on database/factories/TrainingSessionGroupFactory.php
> +     * Define the model's default state.
deze weghalen

2023-06-19 09:48 UTC, ChendoMonster404 approved these changes
LGTM!

2023-06-19 09:48 UTC, merged