Feature/afsplitsen nieuws paginas
Mees-H/SCRUM-SOp pull request #93
Opened 2023-06-16 12:21 UTC by lauravdh1

# Definition of Done

## Functionele definities 

- [x] De acceptatiecriteria van de user story zijn gehaald. 

- [ ] Elk stuk werk is nagekeken door minimaal 2 andere programmeurs. 

- [x] Het programma wordt getest en werkt op 2 verschillende browsers (Google Chrome & Edge). 

### Toegankelijkheid 

- [X] De website moet voor iedereen te navigeren zijn. 

- [X] Inclusief mensen met een beperking. 

- [X] De website dient volledig navigeerbaar te zijn zonder gebruik te maken van een muis. 

- [X] Dit betekent navigeren via de tab en enter toets met behulp van spraak. 

- [X] De knoppen zijn voorzien van duidelijke beschrijvingen. 

- [X] De knoppen zijn groot genoeg om de tekst te bevatten. 

- [X] De teksten op de website bevatten geen spelfouten en zijn duidelijk geformuleerd. 

- [X] Zorg voor voldoende contrast. 

- [X] Contrast wordt getest met deze tool: https://webaim.org/resources/contrastchecker/  

- [X] De WCAG AAA test moet pass teruggeven. 

- [X] Maak geen gebruik van hyperlinks met een klik hier maar gebruik een betekenisvolle beschrijving.  

Zoals: Lees meer over regulering. 

- [X] Maak korte en inhoudelijke pagina’s. 

## Technische definities 

### Reviewers 

- [ ] Elke pull request is door minimaal 2 personen nagekeken. 

- [ ] Een taak wordt pas als af beschouwd zodra hij is goedgekeurd door de 2 reviewers en samengevoegd is op de juiste branch. 

- [ ] De reviewer doorloopt de happy flow. 

- [ ] Hierbij maakt de reviewer gebruik van de juiste werkwijze van de website. 

- [ ] De reviewer probeert d.m.v. onjuist gebruik van de website de website te breken. 

- [ ] Dit kan hij/zij doen door verkeerde invoer van velden. 

- [ ] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

### Ontwikkelaar 

- [X] Er is geen SQL injection mogelijk  

- [ ] Alle invoervelden zijn voorzien van een regex. 

- [ ] Deze regex zorgt ervoor dat alleen het noodzakelijke ingevoerd kan worden. 

- [X] De coding guidlines zijn aangehouden. 

- [X] De geschreven code compileert. 

- [X] De geschreven code veroorzaakt geen crashes. 

- [X] Code levert geen complicaties op met de AVG-wetgeving. 

- [X] Dusk tests worden geschreven voor de happy flow en minimaal 1 bad flow. 

- [X] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

- [X] De siteMap en navigatiebalk zijn geüpdatet op basis van de aanpassingen. 

### Toegankelijkheid 

- [X] Houd je aan de standaarden voor het web. 

- [X] De website moet door gebruik van tab te navigeren zijn. 

- [X] Voeg een alt-tekst toe bij niet-tekstuele-content met betekenisvolle informatie. 

- [X] Maak geen gebruik van spaties. 

- [X] De knoppen hebben een minimaal formaat van 21x30px. 

- [X] Maak gebruik van een rustige layout. 

- [X] Maak gebruik van koppen met h1, h2, h3 tags. 

- [X] Maak gebruik van beschrijvende kopteksten. 

- [X] Duidelijke benaming voor knoppen. 

- [ ] Test zelf je code-kwaliteit via www.validator.w3.org  

- [X] Test je syntax. 

- [X] Maak niet alleen gebruik van kleuren om iets duidelijk te maken of uit te leggen maar ook van vormen.  

- [X] Inlaad snelheid zo hoog mogelijk. 

## Summary

Nieuwsbrief en nieuwsartikel van elkaar afgesplitst.

### Description

Nieuwsbrief en nieuwsartikel van elkaar afgesplitst naar nieuwe pagina's.

### User story 

- S8S 464 Als websitebeheerder wil ik dat de nieuwsartikelen los staan van de nieuwsbrieven, zodat ik een beter overzicht kan waarborgen.

### List of acceptation criteria

De nieuwsartikelen en nieuwsbrieven hebben elk een eigen pagina

De pagina’s staan allebei als submenu in de navigatiebalk

Beide pagina’s hebben een menu waarmee snel te navigeren is binnen de pagina

## Challenges and Solutions

### Challenge 1

- Ik moest de styling aanpassen

### Solution 1

- Bootstrap documentatie doorlezen

## User Interface

<img width="949" alt="image" src="https://github.com/Mees-H/SCRUM-SOp/assets/82824855/d7fe057d-6e28-4483-afaa-121b9db12d7f">

<img width="947" alt="image" src="https://github.com/Mees-H/SCRUM-SOp/assets/82824855/d2a4eb15-a99e-4fd4-b37b-327d5e837193">

<img width="947" alt="image" src="https://github.com/Mees-H/SCRUM-SOp/assets/82824855/0e77541b-a499-4f52-9d54-d583506f3428">

<img width="942" alt="image" src="https://github.com/Mees-H/SCRUM-SOp/assets/82824855/fc5f695d-4e5e-46fd-b435-eb2847e2ecd7">

<img width="433" alt="image" src="https://github.com/Mees-H/SCRUM-SOp/assets/82824855/0efc6f0e-aa8e-4a9c-b6ae-4dacc5cdfc46">

2023-06-16 13:00 UTC, PerryWdm requested changes
Heb er echt niet veel op aan te merken, op dat ene puntje na. Verder netjes gedaan!

2023-06-16 13:00 UTC, PerryWdm commented on resources/views/nieuwsbrief/index.blade.php
> +        <link rel="stylesheet" href="{{ asset('css/News.css') }}" />
![image](https://github.com/Mees-H/SCRUM-SOp/assets/101800635/9d7b57af-5074-4b4d-9773-48989921363d)
De footer gaat hier mee. wss heeft dat met een div te maken ofzo

2023-06-17 19:13 UTC, lauravdh1 commented on resources/views/nieuwsbrief/index.blade.php
> +        <link rel="stylesheet" href="{{ asset('css/News.css') }}" />
Jep ik was een </div> vergeten. Is nu gefixt.

2023-06-17 19:58 UTC, PerryWdm approved these changes
Prima!

2023-06-18 12:08 UTC, EvaVanGurp approved these changes
Klein dingetje, verder is alles goed

2023-06-18 12:08 UTC, EvaVanGurp commented on public/css/News.css
> +    /* width: 40em; */
Haal de uitgecommente code nog ff weg

2023-06-19 07:57 UTC, merged