Upload Slider image notification
Mees-H/SCRUM-SOp pull request #94
Opened 2023-06-16 13:24 UTC by PerryWdm

# Definition of Done

## Functionele definities 

- [x] De acceptatiecriteria van de user story zijn gehaald. 

- [ ] Elk stuk werk is nagekeken door minimaal 2 andere programmeurs. 

- [x] Het programma wordt getest en werkt op 2 verschillende browsers (Google Chrome & Edge). 

### Toegankelijkheid 

- [x] De website moet voor iedereen te navigeren zijn. 

- [x] Inclusief mensen met een beperking. 

- [x] De website dient volledig navigeerbaar te zijn zonder gebruik te maken van een muis. 

- [x] Dit betekent navigeren via de tab en enter toets met behulp van spraak. 

- [x] De knoppen zijn voorzien van duidelijke beschrijvingen. 

- [x] De knoppen zijn groot genoeg om de tekst te bevatten. 

- [x] De teksten op de website bevatten geen spelfouten en zijn duidelijk geformuleerd. 

- [x] Zorg voor voldoende contrast. 

- [x] Contrast wordt getest met deze tool: https://webaim.org/resources/contrastchecker/  

- [x] De WCAG AAA test moet pass teruggeven. 

- [x] Maak geen gebruik van hyperlinks met een klik hier maar gebruik een betekenisvolle beschrijving.  

Zoals: Lees meer over regulering. 

- [x] Maak korte en inhoudelijke pagina’s. 

## Technische definities 

### Reviewers 

- [ ] Elke pull request is door minimaal 2 personen nagekeken. 

- [ ] Een taak wordt pas als af beschouwd zodra hij is goedgekeurd door de 2 reviewers en samengevoegd is op de juiste branch. 

- [ ] De reviewer doorloopt de happy flow. 

- [ ] Hierbij maakt de reviewer gebruik van de juiste werkwijze van de website. 

- [ ] De reviewer probeert d.m.v. onjuist gebruik van de website de website te breken. 

- [ ] Dit kan hij/zij doen door verkeerde invoer van velden. 

- [ ] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

### Ontwikkelaar 

- [x] Er is geen SQL injection mogelijk  

- [x] Alle invoervelden zijn voorzien van een regex. 

- [x] Deze regex zorgt ervoor dat alleen het noodzakelijke ingevoerd kan worden. 

- [x] De coding guidlines zijn aangehouden. 

- [x] De geschreven code compileert. 

- [x] De geschreven code veroorzaakt geen crashes. 

- [x] Code levert geen complicaties op met de AVG-wetgeving. 

- [x] Dusk tests worden geschreven voor de happy flow en minimaal 1 bad flow. 

- [x] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

- [x] De siteMap en navigatiebalk zijn geüpdatet op basis van de aanpassingen. 

### Toegankelijkheid 

- [x] Houd je aan de standaarden voor het web. 

- [x] De website moet door gebruik van tab te navigeren zijn. 

- [x] Voeg een alt-tekst toe bij niet-tekstuele-content met betekenisvolle informatie. 

- [x] Maak geen gebruik van spaties. 

- [x] De knoppen hebben een minimaal formaat van 21x30px. 

- [x] Maak gebruik van een rustige layout. 

- [x] Maak gebruik van koppen met h1, h2, h3 tags. 

- [x] Maak gebruik van beschrijvende kopteksten. 

- [x] Duidelijke benaming voor knoppen. 

- [x] Test zelf je code-kwaliteit via www.validator.w3.org  

- [x] Test je syntax. 

- [x] Maak niet alleen gebruik van kleuren om iets duidelijk te maken of uit te leggen maar ook van vormen.  

- [x] Inlaad snelheid zo hoog mogelijk. 

## Summary

### Description

- Het krijgen van een melding wanneer er een actie is uitgevoerd door de admin op de slider pagina

### User story 

- S8S 405 Als websitebeheerder wil ik dat ik duidelijk feedback ontvang als iets goed/fout gaat bij het uploaden van sliders, zodat ik weet wat ik daarna moet doen

### List of acceptation criteria

 De slider geeft een foutmelding als je iets probeert te uploaden zonder afbeelding

De slider geeft een succesbericht als de slider geupload is

De slider geeft een succesbericht als een afbeelding uit de slider verwijderd is.

## Challenges and Solutions

### Challenge 1

- nothing

### Solution 1

- nothing

## User Interface

-![image](https://github.com/Mees-H/SCRUM-SOp/assets/101800635/f4b6ec0c-cb89-4190-bb88-55d59eb6b23a)

2023-06-16 17:30 UTC, ChendoMonster404 requested changes
heb 1 dingetje gevonden die je even snel kunt aanpassen, verder wacht ik op reactie op mijn discord bericht.

2023-06-16 17:30 UTC, ChendoMonster404 commented on resources/views/slider/index.blade.php
> +                            Toevoegen</a>
Ik stoor me er een beetje aan dat Foto en Toevoegen op een andere regel staan

2023-06-18 11:00 UTC, ChendoMonster404 approved these changes
alles werkt

2023-06-19 08:15 UTC, Qoen1 approved these changes

2023-06-19 08:17 UTC, merged