Feature/update footer
Mees-H/SCRUM-SOp pull request #95
Opened 2023-06-16 16:22 UTC by ChendoMonster404

# Definition of Done

## Functionele definities 

- [ ] De acceptatiecriteria van de user story zijn gehaald. 

- [ ] Elk stuk werk is nagekeken door minimaal 2 andere programmeurs. 

- [ ] Het programma wordt getest en werkt op 2 verschillende browsers (Google Chrome & Edge). 

### Toegankelijkheid 

- [ ] De website moet voor iedereen te navigeren zijn. 

- [ ] Inclusief mensen met een beperking. 

- [ ] De website dient volledig navigeerbaar te zijn zonder gebruik te maken van een muis. 

- [ ] Dit betekent navigeren via de tab en enter toets met behulp van spraak. 

- [ ] De knoppen zijn voorzien van duidelijke beschrijvingen. 

- [ ] De knoppen zijn groot genoeg om de tekst te bevatten. 

- [ ] De teksten op de website bevatten geen spelfouten en zijn duidelijk geformuleerd. 

- [ ] Zorg voor voldoende contrast. 

- [ ] Contrast wordt getest met deze tool: https://webaim.org/resources/contrastchecker/  

- [ ] De WCAG AAA test moet pass teruggeven. 

- [ ] Maak geen gebruik van hyperlinks met een klik hier maar gebruik een betekenisvolle beschrijving.  

Zoals: Lees meer over regulering. 

- [ ] Maak korte en inhoudelijke pagina’s. 

## Technische definities 

### Reviewers 

- [ ] Elke pull request is door minimaal 2 personen nagekeken. 

- [ ] Een taak wordt pas als af beschouwd zodra hij is goedgekeurd door de 2 reviewers en samengevoegd is op de juiste branch. 

- [ ] De reviewer doorloopt de happy flow. 

- [ ] Hierbij maakt de reviewer gebruik van de juiste werkwijze van de website. 

- [ ] De reviewer probeert d.m.v. onjuist gebruik van de website de website te breken. 

- [ ] Dit kan hij/zij doen door verkeerde invoer van velden. 

- [ ] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

### Ontwikkelaar 

- [ ] Er is geen SQL injection mogelijk  

- [ ] Alle invoervelden zijn voorzien van een regex. 

- [ ] Deze regex zorgt ervoor dat alleen het noodzakelijke ingevoerd kan worden. 

- [ ] De coding guidlines zijn aangehouden. 

- [ ] De geschreven code compileert. 

- [ ] De geschreven code veroorzaakt geen crashes. 

- [ ] Code levert geen complicaties op met de AVG-wetgeving. 

- [ ] Dusk tests worden geschreven voor de happy flow en minimaal 1 bad flow. 

- [ ] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

- [ ] De siteMap en navigatiebalk zijn geüpdatet op basis van de aanpassingen. 

### Toegankelijkheid 

- [ ] Houd je aan de standaarden voor het web. 

- [ ] De website moet door gebruik van tab te navigeren zijn. 

- [ ] Voeg een alt-tekst toe bij niet-tekstuele-content met betekenisvolle informatie. 

- [ ] Maak geen gebruik van spaties. 

- [ ] De knoppen hebben een minimaal formaat van 21x30px. 

- [ ] Maak gebruik van een rustige layout. 

- [ ] Maak gebruik van koppen met h1, h2, h3 tags. 

- [ ] Maak gebruik van beschrijvende kopteksten. 

- [ ] Duidelijke benaming voor knoppen. 

- [ ] Test zelf je code-kwaliteit via www.validator.w3.org  

- [ ] Test je syntax. 

- [ ] Maak niet alleen gebruik van kleuren om iets duidelijk te maken of uit te leggen maar ook van vormen.  

- [ ] Inlaad snelheid zo hoog mogelijk. 

## Summary

### Description

- (Description of the functionality)

### User story 

- (What user story did you complete?)

### List of acceptation criteria

- (All acceptation criteria of the user story)

## Challenges and Solutions

### Challenge 1

- (What was difficult?)

### Solution 1

- (How did you solve it?)

## User Interface

- (Image screenshot of UI with description here)

2023-06-17 10:02 UTC, Qoen1 requested changes
zie discord

2023-06-18 19:05 UTC, JoshavEngelen approved these changes

2023-06-18 19:05 UTC, JoshavEngelen commented on app/Http/Controllers/FooterController.php
> +            'rsin' => ['required','max:9','min:8'],
RSIN is altijd 9 cijfers

2023-06-19 10:45 UTC, Qoen1 approved these changes
lgtm

2023-06-19 10:49 UTC, merged