Feature/banner
Mees-H/SCRUM-SOp pull request #96
Opened 2023-06-16 18:41 UTC by JoshavEngelen

# Definition of Done

## Functionele definities 

- [x] De acceptatiecriteria van de user story zijn gehaald. 

- [ ] Elk stuk werk is nagekeken door minimaal 2 andere programmeurs. 

- [x] Het programma wordt getest en werkt op 2 verschillende browsers (Google Chrome & Edge). 

### Toegankelijkheid 

- [x] De website moet voor iedereen te navigeren zijn. 

- [x] Inclusief mensen met een beperking. 

- [x] De website dient volledig navigeerbaar te zijn zonder gebruik te maken van een muis. 

- [x] Dit betekent navigeren via de tab en enter toets met behulp van spraak. 

- [x] De knoppen zijn voorzien van duidelijke beschrijvingen. 

- [x] De knoppen zijn groot genoeg om de tekst te bevatten. 

- [x] De teksten op de website bevatten geen spelfouten en zijn duidelijk geformuleerd. 

- [x] Zorg voor voldoende contrast. 

- [x] Contrast wordt getest met deze tool: https://webaim.org/resources/contrastchecker/  

- [x] De WCAG AAA test moet pass teruggeven. 

- [x] Maak geen gebruik van hyperlinks met een klik hier maar gebruik een betekenisvolle beschrijving.  

Zoals: Lees meer over regulering. 

- [x] Maak korte en inhoudelijke pagina’s. 

## Technische definities 

### Reviewers 

- [ ] Elke pull request is door minimaal 2 personen nagekeken. 

- [ ] Een taak wordt pas als af beschouwd zodra hij is goedgekeurd door de 2 reviewers en samengevoegd is op de juiste branch. 

- [ ] De reviewer doorloopt de happy flow. 

- [ ] Hierbij maakt de reviewer gebruik van de juiste werkwijze van de website. 

- [ ] De reviewer probeert d.m.v. onjuist gebruik van de website de website te breken. 

- [ ] Dit kan hij/zij doen door verkeerde invoer van velden. 

- [ ] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

### Ontwikkelaar 

- [x] Er is geen SQL injection mogelijk  

- [ ] N.V.T. Alle invoervelden zijn voorzien van een regex. 

- [ ] N.V.T. Deze regex zorgt ervoor dat alleen het noodzakelijke ingevoerd kan worden. 

- [x] De coding guidelines zijn aangehouden. 

- [x] De geschreven code compileert. 

- [x] De geschreven code veroorzaakt geen crashes. 

- [x] Code levert geen complicaties op met de AVG-wetgeving. 

- [ ] Dusk tests worden geschreven voor de happy flow en minimaal 1 bad flow. 

- [x] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

- [x] De siteMap en navigatiebalk zijn geüpdatet op basis van de aanpassingen. 

### Toegankelijkheid 

- [x] Houd je aan de standaarden voor het web. 

- [x] De website moet door gebruik van tab te navigeren zijn. 

- [x] Voeg een alt-tekst toe bij niet-tekstuele-content met betekenisvolle informatie. 

- [x] Maak geen gebruik van spaties. 

- [x] De knoppen hebben een minimaal formaat van 21x30px. 

- [x] Maak gebruik van een rustige layout. 

- [x] Maak gebruik van koppen met h1, h2, h3 tags. 

- [x] Maak gebruik van beschrijvende kopteksten. 

- [x] Duidelijke benaming voor knoppen. 

- [ ] N.V.T. Test zelf je code-kwaliteit via www.validator.w3.org  

- [x] Test je syntax. 

- [x] Maak niet alleen gebruik van kleuren om iets duidelijk te maken of uit te leggen maar ook van vormen.  

- [x] Inlaad snelheid zo hoog mogelijk. 

## Summary

### Description

- Je kunt nu banners toevoegen en wijzigen van pagina's die in de database staan

### User story 

- S8S-64 Als websitebeheerder wil ik foto's als banners op pagina's zodat de website er levendig uit ziet

### List of acceptation criteria

- Je kan per websitebezoekerspagina de banner aanpassen
- De CRUD pagina staat onder de Foto’s dropdown van de webbeheerder.
- Voor elke pagina wordt de titel van de pagina weergegeven, de foto van de banner en een upload knop waar je een nieuwe banner kan uploaden (CRUD overzicht)
- Je kan dit aanpassen op een nieuwe pagina
- Default banner is leeg
- De banner pakt de volledige breedte van de pagina.
- De titel van de pagina wordt in het midden van de banner weergegeven.
- De titel mag niet gewijzigd worden.
- De slider moet aangepast worden naar dat deze de volledige breedte opneemt van de pagina
- De hoofdpagina heeft geen banner.

## Challenges and Solutions

### Challenge 1

- Er was een error met de routing opgetreden.

### Solution 1

- Dit werd opgelost door een aparte route aan te maken.

## User Interface

CRUD Pagina van de banners
![image](https://github.com/Mees-H/SCRUM-SOp/assets/103433509/c606e521-4337-4530-a2a2-c110cd9449da)

Weergave van een banner op de trainingpagina
![image](https://github.com/Mees-H/SCRUM-SOp/assets/103433509/ce4e7765-4836-40ca-9dcb-4fb762f88035)

2023-06-17 18:23 UTC, PerryWdm commented on app/Http/Requests/UploadImageRequest.php
>          return [
Png's worden niet geaccepteerd

2023-06-17 18:32 UTC, PerryWdm commented on app/Http/Requests/UploadImageRequest.php
>          return [
Maar ik denk dat we in ieder geval de grootte iets moeten ophogen, anders vallen er heel veel foto's af.

2023-06-17 19:10 UTC, PerryWdm requested changes
Nog een paar puntjes, verder ziet het er wat mij betreft prima uit

2023-06-17 19:10 UTC, PerryWdm commented on resources/views/banners/index.blade.php
> +            </table>
Ik denk een div'je te veel
![image](https://github.com/Mees-H/SCRUM-SOp/assets/101800635/978ae36b-1c7f-419a-9e3a-744532a6c035)

2023-06-17 19:10 UTC, PerryWdm commented on resources/views/banners/index.blade.php
> +            </table>
de footer staat niet goed

2023-06-17 19:10 UTC, PerryWdm commented on tests/Browser/BannerTest.php
> +
Misschien nog een of twee testen erbij?

2023-06-18 20:58 UTC, Qoen1 approved these changes

2023-06-19 08:39 UTC, PerryWdm approved these changes
Prima

2023-06-19 08:43 UTC, Qoen1 requested changes
nee

2023-06-19 10:39 UTC, Qoen1 approved these changes

2023-06-19 10:41 UTC, merged