Feature/formremembrance
Mees-H/SCRUM-SOp pull request #99
Opened 2023-06-17 12:59 UTC by Mees-H

# Definition of Done

## Functionele definities 

- [x] De acceptatiecriteria van de user story zijn gehaald. 

- [ ] Elk stuk werk is nagekeken door minimaal 2 andere programmeurs. 

- [x] Het programma wordt getest en werkt op 2 verschillende browsers (Google Chrome & Edge). 

### Toegankelijkheid 

- [x] De website moet voor iedereen te navigeren zijn. 

- [x] Inclusief mensen met een beperking. 

- [x] De website dient volledig navigeerbaar te zijn zonder gebruik te maken van een muis. 

- [x] Dit betekent navigeren via de tab en enter toets met behulp van spraak. 

- [x] De knoppen zijn voorzien van duidelijke beschrijvingen. 

- [x] De knoppen zijn groot genoeg om de tekst te bevatten. 

- [x] De teksten op de website bevatten geen spelfouten en zijn duidelijk geformuleerd. 

- [x] Zorg voor voldoende contrast. 

- [x] Contrast wordt getest met deze tool: https://webaim.org/resources/contrastchecker/  

- [x] De WCAG AAA test moet pass teruggeven. 

- [x] Maak geen gebruik van hyperlinks met een klik hier maar gebruik een betekenisvolle beschrijving.  

Zoals: Lees meer over regulering. 

- [x] Maak korte en inhoudelijke pagina’s. 

## Technische definities 

### Reviewers 

- [ ] Elke pull request is door minimaal 2 personen nagekeken. 

- [ ] Een taak wordt pas als af beschouwd zodra hij is goedgekeurd door de 2 reviewers en samengevoegd is op de juiste branch. 

- [ ] De reviewer doorloopt de happy flow. 

- [ ] Hierbij maakt de reviewer gebruik van de juiste werkwijze van de website. 

- [ ] De reviewer probeert d.m.v. onjuist gebruik van de website de website te breken. 

- [ ] Dit kan hij/zij doen door verkeerde invoer van velden. 

- [ ] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

### Ontwikkelaar 

- [x] Er is geen SQL injection mogelijk  

- [ ] Alle invoervelden zijn voorzien van een regex. 

- [ ] Deze regex zorgt ervoor dat alleen het noodzakelijke ingevoerd kan worden. 

- [x] De coding guidlines zijn aangehouden. 

- [x] De geschreven code compileert. 

- [x] De geschreven code veroorzaakt geen crashes. 

- [x] Code levert geen complicaties op met de AVG-wetgeving. 

- [x] Dusk tests worden geschreven voor de happy flow en minimaal 1 bad flow. 

- [x] Views zijn getest op responsiveness (mobiel, tablet, desktop) door middel van UI testen. 

- [x] De siteMap en navigatiebalk zijn geüpdatet op basis van de aanpassingen. 

### Toegankelijkheid 

- [x] Houd je aan de standaarden voor het web. 

- [x] De website moet door gebruik van tab te navigeren zijn. 

- [x] Voeg een alt-tekst toe bij niet-tekstuele-content met betekenisvolle informatie. 

- [x] Maak geen gebruik van spaties. 

- [x] De knoppen hebben een minimaal formaat van 21x30px. 

- [x] Maak gebruik van een rustige layout. 

- [x] Maak gebruik van koppen met h1, h2, h3 tags. 

- [x] Maak gebruik van beschrijvende kopteksten. 

- [x] Duidelijke benaming voor knoppen. 

- [x] Test zelf je code-kwaliteit via www.validator.w3.org  

- [x] Test je syntax. 

- [x] Maak niet alleen gebruik van kleuren om iets duidelijk te maken of uit te leggen maar ook van vormen.  

- [x] Inlaad snelheid zo hoog mogelijk. 

## Summary

### Description

De informatie van alle formulieren wordt nu voor de gebruiker onthouden na een verkeerde invulling van formulieren

### User story 

Als websitebezoeker wil ik dat mijn informatie onthouden wordt als ik een formulier verkeerd invul, zodat ik minder tijd kwijt ben aan het invullen van informatie

### List of acceptation criteria

Als er informatie verkeerd ingevuld is in een formulier wordt het onthouden op pagina verversing

Wachtwoorden en andere gevoelige informatie worden niet onthouden

## Challenges and Solutions

### Challenge 1

Radio buttons en checkboxes waren lastig om te onthouden

### Solution 1

In de code stond al een voorbeeld van hoe het kon, heb ik overgenomen

## User Interface

NVT

2023-06-17 13:00 UTC, Mees-H commented
Dusk testen heb ik op de banner branch opgelost, en verder breken dit geen nieuwe testen

2023-06-17 18:34 UTC, lauravdh1 approved these changes

2023-06-19 08:40 UTC, webwizard678 requested changes
kleine dingetjes

2023-06-19 08:40 UTC, webwizard678 commented on resources/views/members/create.blade.php
> +                <label>Groepen:</label>
Zet het * weer terug. het is namelijk wel verplicht

2023-06-19 08:40 UTC, webwizard678 commented on resources/views/profile/partials/update-password-form.blade.php
> +                <input type="text" class="form-control" id="huidig_wachtwoord" name="huidig_wachtwoord" value="{{ old('huidig_wachtwoord') }}">
Onthoud geen wachtwoorden

2023-06-19 08:40 UTC, webwizard678 commented on resources/views/profile/partials/update-password-form.blade.php
> +                <input type="password" class="form-control" id="wachtwoord" name="wachtwoord" value="{{ old('wachtwoord') }}">
hier ook

2023-06-19 08:40 UTC, webwizard678 commented on resources/views/profile/partials/update-password-form.blade.php
>              </div>
hier ook

2023-06-19 10:06 UTC, webwizard678 approved these changes
lgtm

2023-06-19 10:15 UTC, merged